### PR TITLE
feat: add presubmit for image format

### PR DESCRIPTION
**Pull request by BobyMCbobs**
checks the image ref format.
ensures only images with tag and digest are synced

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
regex needs some work

**Comment by BobyMCbobs** [comment]
it is working now!

**Review by Mossman1215 — APPROVED** [review]
Presubmit checks are awesome :+1:

**Comment by BobyMCbobs** [comment]
> Presubmit checks are awesome +1

@Mossman1215, absolutely! Thank you!

**Pull request merged**
