### PR TITLE
Arcgis dependency updates

### PR DESCRIPTION
**Pull request by CallumNZ**
Updated `numpy`, `pandas`, and `geopandas`.
Ran integration test with downstream application, works fine.

### CODE REVIEW

**Comment by Mossman1215** [comment]
minor quibble regarding the `nfc:` prefix
this is a change so should be marked with a `fix:` prefix
nfc would be for non technical change like documentation or user access changes

**Comment by CallumNZ** [comment]
oh! ok, I don't understand `nfc` 😅

**Comment by Mossman1215** [comment]
> oh! ok, I don't understand `nfc` 😅

no worries

> Commit Body                  FAILED        Commit body is empty 

needs a body in the commit @CallumNZ

**Review by Mossman1215 — APPROVED** [review]
lets give it a go

**Pull request merged**
